trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'Azure-Service-Connection'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  displayName: 'Terraform Init'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform init

- task: AzureCLI@2
  displayName: 'Terraform Apply'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform apply -auto-approve